---
# tasks file for iptables

- name: Set IPtables binary
  alternatives:
    name: iptables
    path: /usr/sbin/iptables-legacy
  when: ansible_distribution == 'Debian' and ansible_distribution_release == 'buster'

- name: Set IP6tables binary
  alternatives:
    name: ip6tables
    path: /usr/sbin/ip6tables-legacy
  when: ansible_distribution == 'Debian' and ansible_distribution_release == 'buster'

- name: Set IPtables rules
  iptables_raw:
    name: fusionpbx
    rules: |
      -A INPUT -i lo -j ACCEPT
      -A INPUT -m state --state ESTABLISHED,RELATED -j ACCEPT
      -A INPUT -j DROP -p udp --dport 5060:5091 -m string --string "friendly-scanner" --algo bm --icase
      -A INPUT -j DROP -p tcp --dport 5060:5091 -m string --string "friendly-scanner" --algo bm --icase
      -A INPUT -j DROP -p udp --dport 5060:5091 -m string --string "sipcli/" --algo bm --icase
      -A INPUT -j DROP -p tcp --dport 5060:5091 -m string --string "sipcli/" --algo bm --icase
      -A INPUT -j DROP -p udp --dport 5060:5091 -m string --string "VaxSIPUserAgent/" --algo bm --icase
      -A INPUT -j DROP -p tcp --dport 5060:5091 -m string --string "VaxSIPUserAgent/" --algo bm --icase
      -A INPUT -j DROP -p udp --dport 5060:5091 -m string --string "pplsip" --algo bm --icase
      -A INPUT -j DROP -p tcp --dport 5060:5091 -m string --string "pplsip" --algo bm --icase
      -A INPUT -j DROP -p udp --dport 5060:5091 -m string --string "system " --algo bm --icase
      -A INPUT -j DROP -p tcp --dport 5060:5091 -m string --string "system " --algo bm --icase
      -A INPUT -j DROP -p udp --dport 5060:5091 -m string --string "exec." --algo bm --icase
      -A INPUT -j DROP -p tcp --dport 5060:5091 -m string --string "exec." --algo bm --icase
      -A INPUT -j DROP -p udp --dport 5060:5091 -m string --string "multipart/mixed;boundary" --algo bm --icase
      -A INPUT -j DROP -p tcp --dport 5060:5091 -m string --string "multipart/mixed;boundary" --algo bm --icase
      -A INPUT -p tcp --dport 22 -j ACCEPT
      -A INPUT -p tcp --dport 80 -j ACCEPT
      -A INPUT -p tcp --dport 443 -j ACCEPT
      -A INPUT -p tcp --dport 7443 -j ACCEPT
      -A INPUT -p tcp --dport 5060:5091 -j ACCEPT
      -A INPUT -p udp --dport 5060:5091 -j ACCEPT
      -A INPUT -p udp --dport 16384:32768 -j ACCEPT
      -A INPUT -p icmp --icmp-type echo-request -j ACCEPT
      -A INPUT -p udp --dport 1194 -j ACCEPT
      -t mangle -A OUTPUT -p udp -m udp --sport 16384:32768 -j DSCP --set-dscp 46
      -t mangle -A OUTPUT -p udp -m udp --sport 5060:5091 -j DSCP --set-dscp 26
      -t mangle -A OUTPUT -p tcp -m tcp --sport 5060:5091 -j DSCP --set-dscp 26
      -P INPUT DROP
      -P FORWARD DROP
      -P OUTPUT ACCEPT

- name: Set IPtables Autosave
  debconf:
    name: iptables-persistent
    question: iptables-persistent/autosave_v4
    value: true
    vtype: boolean

- name: Set IP6tables Autosave
  debconf:
    name: iptables-persistent
    question: iptables-persistent/autosave_v6
    value: true
    vtype: boolean

- name: Install iptables-persistent
  apt:
    pkg: iptables-persistent
    state: present