---
# tasks file for fusionpbx

- name: Update all packages to their latest version
  ansible.builtin.apt:
    name: "*"
    state: latest
    update_cache: yes

- name: Install prerequisites
  ansible.builtin.apt:
    pkg:
    - sudo
    - git
    - wget
    - lsb-release
    - systemd
    - systemd-sysv
    - ca-certificates
    - dialog
    - nano
    - net-tools
    - snmpd
    - gpg

- name: SNMP - Enable read only public access
  ansible.builtin.lineinfile:
    path: /etc/snmp/snmpd.conf
    line: rocommunity public
  register: snmpd_config

- name: SNMP - Restart service
  ansible.builtin.systemd_service:
    name: snmpd
    state: restarted
    enabled: true
  when: snmpd_config is changed

- name: Disable vi Visual Mode
  ansible.builtin.lineinfile:
    path: ~/.vimrc
    line: set mouse-=a
    create: true

- name: Install & Configure IPTables
  import_tasks: iptables.yml

- name: Install sngrep
  import_tasks: sngrep.yml