---
# tasks file for preinstall
- name: Update All Packages
  apt:
    upgrade: dist
    update_cache: yes

- name: Install Software Prerequisites
  apt:
    name:
    - git
    - lsb-release
    - wget
    - systemd
    - systemd-sysv
    - ca-certificates
    - dialog
    - nano
    - net-tools
    - snmpd
    state: present

- name: Configure SNMP
  lineinfile:
    path: /etc/snmp/snmpd.conf
    regexp: '^rocommunity'
    line: rocommunity public

- name: Restart SNMP Daemon
  systemd:
    name: snmpd
    state: restarted